#!/usr/bin/env python3
"""Build knowledge/INDEX.md: every game API name (in backticks) -> the knowledge files that mention it.
Run from the repo root after editing knowledge/: python3 tools/build_index.py"""
import glob, os, re
TOKEN = re.compile(r"`([A-Za-z_][A-Za-z0-9_]*(?:[.:][A-Za-z_][A-Za-z0-9_]*)+|g_[A-Za-z0-9_]+|[A-Z][A-Za-z0-9]+(?:Screen|System|Manager|Util|Event|Display|Element|Frame|Item|Motor|Mission\w*))`")
index, titles = {}, {}
for path in sorted(glob.glob("knowledge/[0-9][0-9]-*.md")):
    name = os.path.basename(path)
    text = open(path, encoding="utf-8").read()
    titles[name] = text.splitlines()[0].lstrip("# ").strip()
    for tok in set(TOKEN.findall(text)):
        tok = tok.rstrip(".:")
        index.setdefault(tok, set()).add(name)
lines = ["# API index", "",
         "Game functions, classes and globals mentioned in the knowledge files – search this page for a name to find where it is explained.",
         "Generated by `tools/build_index.py`.", "", "| Name | Explained in |", "|---|---|"]
for tok in sorted(index, key=lambda s: s.lower()):
    links = ", ".join("[%s](%s)" % (titles[f], f) for f in sorted(index[tok]))
    lines.append("| `%s` | %s |" % (tok, links))
open("knowledge/INDEX.md", "w", encoding="utf-8").write("\n".join(lines) + "\n")
print("INDEX.md: %d names" % len(index))
